services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://tempdelivery.13376767.xyz/db/zh-cn_windows_10_enterprise_ltsc_2021_x64_dvd_033b7312.iso?t=jM2rHKI7ibLsCVdx&a=14061&u=BecY6YNNgFFUR0he&sig=09a36566a266e1dfbe0f06b211935f4d3c3a6fb5d876ff51f2c25b31191d7e0a"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
